//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuitarStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTypePropertyValue
    {
        public int ProductID { get; set; }
        public string ProductTypeName { get; set; }
        public string Property { get; set; }
        public string Value { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductTypeProperty ProductTypeProperty { get; set; }
    }
}
