//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuitarStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTypeProperty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductTypeProperty()
        {
            this.ProductTypePropertyValues = new HashSet<ProductTypePropertyValue>();
        }
    
        public string ProductTypeName { get; set; }
        public string Property { get; set; }
    
        public virtual ProductType ProductType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductTypePropertyValue> ProductTypePropertyValues { get; set; }
    }
}
